### ISSUE TITLE
Hello, this happened when i right click the chest, nothing happened when i left click.

### ISSUE THREAD

**Issue by realsillysushi** [shmkane/SellStick#43]
Server 1.12.2 using the latest version.
`
> [09:07:41 ERROR]: Could not pass event PlayerInteractEvent to SellStick v9.1.0
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Skyblock.jar:git-Spigot-2cf50f0-2b93d83]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Skyblock.jar:git-Spigot-2cf50f0-2b93d83]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [Skyblock.jar:git-Spigot-2cf50f0-2b93d83]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [Skyblock.jar:git-Spigot-2cf50f0-2b93d83]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) [Skyblock.jar:git-Spigot-2cf50f0-2b93d83]
at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:458) [Skyblock.jar:git-Spigot-2cf50f0-2b93d83]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:951) [Skyblock.jar:git-Spigot-2cf50f0-2b93d83]
at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [Skyblock.jar:git-Spigot-2cf50f0-2b93d83]
at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [Skyblock.jar:git-Spigot-2cf50f0-2b93d83]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Skyblock.jar:git-Spigot-2cf50f0-2b93d83]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [Skyblock.jar:git-Spigot-2cf50f0-2b93d83]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [Skyblock.jar:git-Spigot-2cf50f0-2b93d83]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [Skyblock.jar:git-Spigot-2cf50f0-2b93d83]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [Skyblock.jar:git-Spigot-2cf50f0-2b93d83]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [Skyblock.jar:git-Spigot-2cf50f0-2b93d83]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NoSuchMethodError: com.earth2me.essentials.Worth.getPrice(Lcom/earth2me/essentials/IEssentials;Lorg/bukkit/inventory/ItemStack;)Ljava/math/BigDecimal;
at com.shmkane.sellstick.PlayerListener.calculateWorth(PlayerListener.java:296) ~[?:?]
at com.shmkane.sellstick.PlayerListener.onUse(PlayerListener.java:451) ~[?:?]
at sun.reflect.GeneratedMethodAccessor145.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[Skyblock.jar:git-Spigot-2cf50f0-2b93d83]
... 17 more`

**Comment by shmkane** [comment]
Does this issue still exist

**Comment by shmkane** [comment]
Seems like you have essentials worth enabled when you dont mean for it to be,

**Comment by JustStanix** [comment]
This is still an issue for me.

**Comment by shmkane** [comment]
Did you disable essentials in the SellSticks config?
